{% set name = "geosdemo" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geosdemo-{{ version }}.tar.gz
  sha256: 23dc96eca35e1dc2adfb68aaee76b397eb63befa55e9c7b6f43481f4eac88f08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - folium
    - ipyleaflet
    - geopandas
    - httpx

test:
  imports:
    - geosdemo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geosdemo
  summary: A python package for interactive mapping.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
